/**:
  ros__parameters:
    build_only: false

    whole_image_detector:
      score_threshold: 0.35
      nms_threshold: 0.7

    map_based_detector:
      min_timestamp_offset: -0.3
      max_timestamp_offset: 0.0

    car_classifier:
      over_exposure_threshold: 0.85
      under_exposure_threshold: -0.83

    pedestrian_classifier:
      over_exposure_threshold: 0.85
      under_exposure_threshold: -0.83
